services:
  db:
    image: "postgres:16.3"
    restart: always
    command: ["postgres", "-c", "log_statement=all"]
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - .server/postgres-data:/var/lib/postgresql/data
      - .server/postgres-logs:/logs:z
      - ./scripts/init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
  # redis:
  #   image: redis:latest
  #   restart: unless-stopped
  #   ports:
  #     - 6379:6379
  mailer:
    image: mailtutan/mailtutan:latest
    restart: unless-stopped
    ports:
      - 1080:1080
      - 1025:1025
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    env_file:
      - .env
    depends_on:
      - db
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: joemama@joemama.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin:/var/lib/pgadmin
      - ./scripts/servers.json:/pgadmin4/servers.json

volumes:
    pgadmin: