services:
  postgres:
    image: "postgres:16.3"
    restart: always
    command: [ "postgres", "-c", "log_statement=all" ]
    environment:
      POSTGRES_PASSWORD: test
    ports:
      - "5432:5432"
    volumes:
      - .server/postgres-data:/var/lib/postgresql/data
      - .server/postgres-logs:/logs:z
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 10