/*
api

Testing ReviewsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_openapi_ReviewsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ReviewsAPIService CreateReview", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ReviewsAPI.CreateReview(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ReviewsAPIService DeleteReview", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var reviewId float64

		httpRes, err := apiClient.ReviewsAPI.DeleteReview(context.Background(), reviewId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ReviewsAPIService GetReview", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var reviewId float64

		resp, httpRes, err := apiClient.ReviewsAPI.GetReview(context.Background(), reviewId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ReviewsAPIService UpdateReview", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var reviewId float64

		resp, httpRes, err := apiClient.ReviewsAPI.UpdateReview(context.Background(), reviewId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
