/*
api

Testing SchoolsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_openapi_SchoolsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test SchoolsAPIService CreateSchool", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.SchoolsAPI.CreateSchool(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SchoolsAPIService DeleteSchool", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id float64

		httpRes, err := apiClient.SchoolsAPI.DeleteSchool(context.Background(), id).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SchoolsAPIService GetSchool", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id float64

		resp, httpRes, err := apiClient.SchoolsAPI.GetSchool(context.Background(), id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SchoolsAPIService SearchSchools", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.SchoolsAPI.SearchSchools(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SchoolsAPIService UpdateSchool", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id float64

		resp, httpRes, err := apiClient.SchoolsAPI.UpdateSchool(context.Background(), id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
