/*
api

Testing CoursesAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_openapi_CoursesAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test CoursesAPIService CreateCourse", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.CoursesAPI.CreateCourse(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CoursesAPIService DeleteCourse", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id float64

		httpRes, err := apiClient.CoursesAPI.DeleteCourse(context.Background(), id).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CoursesAPIService GetCourse", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id float64

		resp, httpRes, err := apiClient.CoursesAPI.GetCourse(context.Background(), id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CoursesAPIService GetCourseProfessors", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id float64

		resp, httpRes, err := apiClient.CoursesAPI.GetCourseProfessors(context.Background(), id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CoursesAPIService SearchCourses", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.CoursesAPI.SearchCourses(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CoursesAPIService UpdateCourse", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id float64

		resp, httpRes, err := apiClient.CoursesAPI.UpdateCourse(context.Background(), id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
