/*
api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the DefaultSelectionPrismaSchoolPayload type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DefaultSelectionPrismaSchoolPayload{}

// DefaultSelectionPrismaSchoolPayload struct for DefaultSelectionPrismaSchoolPayload
type DefaultSelectionPrismaSchoolPayload struct {
	Name string `json:"name"`
	Id   int32  `json:"id"`
}

type _DefaultSelectionPrismaSchoolPayload DefaultSelectionPrismaSchoolPayload

// NewDefaultSelectionPrismaSchoolPayload instantiates a new DefaultSelectionPrismaSchoolPayload object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDefaultSelectionPrismaSchoolPayload(name string, id int32) *DefaultSelectionPrismaSchoolPayload {
	this := DefaultSelectionPrismaSchoolPayload{}
	this.Name = name
	this.Id = id
	return &this
}

// NewDefaultSelectionPrismaSchoolPayloadWithDefaults instantiates a new DefaultSelectionPrismaSchoolPayload object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDefaultSelectionPrismaSchoolPayloadWithDefaults() *DefaultSelectionPrismaSchoolPayload {
	this := DefaultSelectionPrismaSchoolPayload{}
	return &this
}

// GetName returns the Name field value
func (o *DefaultSelectionPrismaSchoolPayload) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *DefaultSelectionPrismaSchoolPayload) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *DefaultSelectionPrismaSchoolPayload) SetName(v string) {
	o.Name = v
}

// GetId returns the Id field value
func (o *DefaultSelectionPrismaSchoolPayload) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *DefaultSelectionPrismaSchoolPayload) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *DefaultSelectionPrismaSchoolPayload) SetId(v int32) {
	o.Id = v
}

func (o DefaultSelectionPrismaSchoolPayload) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DefaultSelectionPrismaSchoolPayload) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["id"] = o.Id
	return toSerialize, nil
}

func (o *DefaultSelectionPrismaSchoolPayload) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDefaultSelectionPrismaSchoolPayload := _DefaultSelectionPrismaSchoolPayload{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDefaultSelectionPrismaSchoolPayload)

	if err != nil {
		return err
	}

	*o = DefaultSelectionPrismaSchoolPayload(varDefaultSelectionPrismaSchoolPayload)

	return err
}

type NullableDefaultSelectionPrismaSchoolPayload struct {
	value *DefaultSelectionPrismaSchoolPayload
	isSet bool
}

func (v NullableDefaultSelectionPrismaSchoolPayload) Get() *DefaultSelectionPrismaSchoolPayload {
	return v.value
}

func (v *NullableDefaultSelectionPrismaSchoolPayload) Set(val *DefaultSelectionPrismaSchoolPayload) {
	v.value = val
	v.isSet = true
}

func (v NullableDefaultSelectionPrismaSchoolPayload) IsSet() bool {
	return v.isSet
}

func (v *NullableDefaultSelectionPrismaSchoolPayload) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDefaultSelectionPrismaSchoolPayload(val *DefaultSelectionPrismaSchoolPayload) *NullableDefaultSelectionPrismaSchoolPayload {
	return &NullableDefaultSelectionPrismaSchoolPayload{value: val, isSet: true}
}

func (v NullableDefaultSelectionPrismaSchoolPayload) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDefaultSelectionPrismaSchoolPayload) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
