/*
api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the InvalidPasswordError type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InvalidPasswordError{}

// InvalidPasswordError struct for InvalidPasswordError
type InvalidPasswordError struct {
	Message PickSchoolErrorMessageOrTypeMessage `json:"message"`
	Type AuthErrorTypeINVALIDPASSWORD `json:"type"`
}

type _InvalidPasswordError InvalidPasswordError

// NewInvalidPasswordError instantiates a new InvalidPasswordError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInvalidPasswordError(message PickSchoolErrorMessageOrTypeMessage, type_ AuthErrorTypeINVALIDPASSWORD) *InvalidPasswordError {
	this := InvalidPasswordError{}
	this.Message = message
	this.Type = type_
	return &this
}

// NewInvalidPasswordErrorWithDefaults instantiates a new InvalidPasswordError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInvalidPasswordErrorWithDefaults() *InvalidPasswordError {
	this := InvalidPasswordError{}
	return &this
}

// GetMessage returns the Message field value
func (o *InvalidPasswordError) GetMessage() PickSchoolErrorMessageOrTypeMessage {
	if o == nil {
		var ret PickSchoolErrorMessageOrTypeMessage
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *InvalidPasswordError) GetMessageOk() (*PickSchoolErrorMessageOrTypeMessage, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *InvalidPasswordError) SetMessage(v PickSchoolErrorMessageOrTypeMessage) {
	o.Message = v
}

// GetType returns the Type field value
func (o *InvalidPasswordError) GetType() AuthErrorTypeINVALIDPASSWORD {
	if o == nil {
		var ret AuthErrorTypeINVALIDPASSWORD
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *InvalidPasswordError) GetTypeOk() (*AuthErrorTypeINVALIDPASSWORD, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *InvalidPasswordError) SetType(v AuthErrorTypeINVALIDPASSWORD) {
	o.Type = v
}

func (o InvalidPasswordError) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InvalidPasswordError) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["message"] = o.Message
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *InvalidPasswordError) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"message",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInvalidPasswordError := _InvalidPasswordError{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varInvalidPasswordError)

	if err != nil {
		return err
	}

	*o = InvalidPasswordError(varInvalidPasswordError)

	return err
}

type NullableInvalidPasswordError struct {
	value *InvalidPasswordError
	isSet bool
}

func (v NullableInvalidPasswordError) Get() *InvalidPasswordError {
	return v.value
}

func (v *NullableInvalidPasswordError) Set(val *InvalidPasswordError) {
	v.value = val
	v.isSet = true
}

func (v NullableInvalidPasswordError) IsSet() bool {
	return v.isSet
}

func (v *NullableInvalidPasswordError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInvalidPasswordError(val *InvalidPasswordError) *NullableInvalidPasswordError {
	return &NullableInvalidPasswordError{value: val, isSet: true}
}

func (v NullableInvalidPasswordError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInvalidPasswordError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


