/*
api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// PickSchoolErrorMessageOrTypeMessage struct for PickSchoolErrorMessageOrTypeMessage
type PickSchoolErrorMessageOrTypeMessage struct {
	MapmapOfStringstring *map[string]string
	String *string
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *PickSchoolErrorMessageOrTypeMessage) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into MapmapOfStringstring
	err = json.Unmarshal(data, &dst.MapmapOfStringstring);
	if err == nil {
		jsonMapmapOfStringstring, _ := json.Marshal(dst.MapmapOfStringstring)
		if string(jsonMapmapOfStringstring) == "{}" { // empty struct
			dst.MapmapOfStringstring = nil
		} else {
			return nil // data stored in dst.MapmapOfStringstring, return on the first match
		}
	} else {
		dst.MapmapOfStringstring = nil
	}

	// try to unmarshal JSON data into String
	err = json.Unmarshal(data, &dst.String);
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			return nil // data stored in dst.String, return on the first match
		}
	} else {
		dst.String = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(PickSchoolErrorMessageOrTypeMessage)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src *PickSchoolErrorMessageOrTypeMessage) MarshalJSON() ([]byte, error) {
	if src.MapmapOfStringstring != nil {
		return json.Marshal(&src.MapmapOfStringstring)
	}

	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in anyOf schemas
}

type NullablePickSchoolErrorMessageOrTypeMessage struct {
	value *PickSchoolErrorMessageOrTypeMessage
	isSet bool
}

func (v NullablePickSchoolErrorMessageOrTypeMessage) Get() *PickSchoolErrorMessageOrTypeMessage {
	return v.value
}

func (v *NullablePickSchoolErrorMessageOrTypeMessage) Set(val *PickSchoolErrorMessageOrTypeMessage) {
	v.value = val
	v.isSet = true
}

func (v NullablePickSchoolErrorMessageOrTypeMessage) IsSet() bool {
	return v.isSet
}

func (v *NullablePickSchoolErrorMessageOrTypeMessage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePickSchoolErrorMessageOrTypeMessage(val *PickSchoolErrorMessageOrTypeMessage) *NullablePickSchoolErrorMessageOrTypeMessage {
	return &NullablePickSchoolErrorMessageOrTypeMessage{value: val, isSet: true}
}

func (v NullablePickSchoolErrorMessageOrTypeMessage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePickSchoolErrorMessageOrTypeMessage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


