/*
api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// SchoolErrorTypeSCHOOLNOTFOUND the model 'SchoolErrorTypeSCHOOLNOTFOUND'
type SchoolErrorTypeSCHOOLNOTFOUND string

// List of SchoolErrorType.SCHOOL_NOT_FOUND
const (
	SCHOOL_NOT_FOUND SchoolErrorTypeSCHOOLNOTFOUND = "SCHOOL_NOT_FOUND"
)

// All allowed values of SchoolErrorTypeSCHOOLNOTFOUND enum
var AllowedSchoolErrorTypeSCHOOLNOTFOUNDEnumValues = []SchoolErrorTypeSCHOOLNOTFOUND{
	"SCHOOL_NOT_FOUND",
}

func (v *SchoolErrorTypeSCHOOLNOTFOUND) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := SchoolErrorTypeSCHOOLNOTFOUND(value)
	for _, existing := range AllowedSchoolErrorTypeSCHOOLNOTFOUNDEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid SchoolErrorTypeSCHOOLNOTFOUND", value)
}

// NewSchoolErrorTypeSCHOOLNOTFOUNDFromValue returns a pointer to a valid SchoolErrorTypeSCHOOLNOTFOUND
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewSchoolErrorTypeSCHOOLNOTFOUNDFromValue(v string) (*SchoolErrorTypeSCHOOLNOTFOUND, error) {
	ev := SchoolErrorTypeSCHOOLNOTFOUND(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for SchoolErrorTypeSCHOOLNOTFOUND: valid values are %v", v, AllowedSchoolErrorTypeSCHOOLNOTFOUNDEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v SchoolErrorTypeSCHOOLNOTFOUND) IsValid() bool {
	for _, existing := range AllowedSchoolErrorTypeSCHOOLNOTFOUNDEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to SchoolErrorType.SCHOOL_NOT_FOUND value
func (v SchoolErrorTypeSCHOOLNOTFOUND) Ptr() *SchoolErrorTypeSCHOOLNOTFOUND {
	return &v
}

type NullableSchoolErrorTypeSCHOOLNOTFOUND struct {
	value *SchoolErrorTypeSCHOOLNOTFOUND
	isSet bool
}

func (v NullableSchoolErrorTypeSCHOOLNOTFOUND) Get() *SchoolErrorTypeSCHOOLNOTFOUND {
	return v.value
}

func (v *NullableSchoolErrorTypeSCHOOLNOTFOUND) Set(val *SchoolErrorTypeSCHOOLNOTFOUND) {
	v.value = val
	v.isSet = true
}

func (v NullableSchoolErrorTypeSCHOOLNOTFOUND) IsSet() bool {
	return v.isSet
}

func (v *NullableSchoolErrorTypeSCHOOLNOTFOUND) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSchoolErrorTypeSCHOOLNOTFOUND(val *SchoolErrorTypeSCHOOLNOTFOUND) *NullableSchoolErrorTypeSCHOOLNOTFOUND {
	return &NullableSchoolErrorTypeSCHOOLNOTFOUND{value: val, isSet: true}
}

func (v NullableSchoolErrorTypeSCHOOLNOTFOUND) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSchoolErrorTypeSCHOOLNOTFOUND) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
