/*
api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ReviewNotFoundError type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ReviewNotFoundError{}

// ReviewNotFoundError struct for ReviewNotFoundError
type ReviewNotFoundError struct {
	Message PickSchoolErrorMessageOrTypeMessage `json:"message"`
	Type    ReviewErrorTypeREVIEWNOTFOUND       `json:"type"`
}

type _ReviewNotFoundError ReviewNotFoundError

// NewReviewNotFoundError instantiates a new ReviewNotFoundError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReviewNotFoundError(message PickSchoolErrorMessageOrTypeMessage, type_ ReviewErrorTypeREVIEWNOTFOUND) *ReviewNotFoundError {
	this := ReviewNotFoundError{}
	this.Message = message
	this.Type = type_
	return &this
}

// NewReviewNotFoundErrorWithDefaults instantiates a new ReviewNotFoundError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReviewNotFoundErrorWithDefaults() *ReviewNotFoundError {
	this := ReviewNotFoundError{}
	return &this
}

// GetMessage returns the Message field value
func (o *ReviewNotFoundError) GetMessage() PickSchoolErrorMessageOrTypeMessage {
	if o == nil {
		var ret PickSchoolErrorMessageOrTypeMessage
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *ReviewNotFoundError) GetMessageOk() (*PickSchoolErrorMessageOrTypeMessage, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *ReviewNotFoundError) SetMessage(v PickSchoolErrorMessageOrTypeMessage) {
	o.Message = v
}

// GetType returns the Type field value
func (o *ReviewNotFoundError) GetType() ReviewErrorTypeREVIEWNOTFOUND {
	if o == nil {
		var ret ReviewErrorTypeREVIEWNOTFOUND
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ReviewNotFoundError) GetTypeOk() (*ReviewErrorTypeREVIEWNOTFOUND, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ReviewNotFoundError) SetType(v ReviewErrorTypeREVIEWNOTFOUND) {
	o.Type = v
}

func (o ReviewNotFoundError) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ReviewNotFoundError) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["message"] = o.Message
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *ReviewNotFoundError) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"message",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varReviewNotFoundError := _ReviewNotFoundError{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varReviewNotFoundError)

	if err != nil {
		return err
	}

	*o = ReviewNotFoundError(varReviewNotFoundError)

	return err
}

type NullableReviewNotFoundError struct {
	value *ReviewNotFoundError
	isSet bool
}

func (v NullableReviewNotFoundError) Get() *ReviewNotFoundError {
	return v.value
}

func (v *NullableReviewNotFoundError) Set(val *ReviewNotFoundError) {
	v.value = val
	v.isSet = true
}

func (v NullableReviewNotFoundError) IsSet() bool {
	return v.isSet
}

func (v *NullableReviewNotFoundError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReviewNotFoundError(val *ReviewNotFoundError) *NullableReviewNotFoundError {
	return &NullableReviewNotFoundError{value: val, isSet: true}
}

func (v NullableReviewNotFoundError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReviewNotFoundError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
