/*
api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the PickUserUsernameOrPassword type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PickUserUsernameOrPassword{}

// PickUserUsernameOrPassword From T, pick a set of properties whose keys are in the union K
type PickUserUsernameOrPassword struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type _PickUserUsernameOrPassword PickUserUsernameOrPassword

// NewPickUserUsernameOrPassword instantiates a new PickUserUsernameOrPassword object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPickUserUsernameOrPassword(username string, password string) *PickUserUsernameOrPassword {
	this := PickUserUsernameOrPassword{}
	this.Username = username
	this.Password = password
	return &this
}

// NewPickUserUsernameOrPasswordWithDefaults instantiates a new PickUserUsernameOrPassword object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPickUserUsernameOrPasswordWithDefaults() *PickUserUsernameOrPassword {
	this := PickUserUsernameOrPassword{}
	return &this
}

// GetUsername returns the Username field value
func (o *PickUserUsernameOrPassword) GetUsername() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Username
}

// GetUsernameOk returns a tuple with the Username field value
// and a boolean to check if the value has been set.
func (o *PickUserUsernameOrPassword) GetUsernameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Username, true
}

// SetUsername sets field value
func (o *PickUserUsernameOrPassword) SetUsername(v string) {
	o.Username = v
}

// GetPassword returns the Password field value
func (o *PickUserUsernameOrPassword) GetPassword() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Password
}

// GetPasswordOk returns a tuple with the Password field value
// and a boolean to check if the value has been set.
func (o *PickUserUsernameOrPassword) GetPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Password, true
}

// SetPassword sets field value
func (o *PickUserUsernameOrPassword) SetPassword(v string) {
	o.Password = v
}

func (o PickUserUsernameOrPassword) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PickUserUsernameOrPassword) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["username"] = o.Username
	toSerialize["password"] = o.Password
	return toSerialize, nil
}

func (o *PickUserUsernameOrPassword) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"username",
		"password",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPickUserUsernameOrPassword := _PickUserUsernameOrPassword{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPickUserUsernameOrPassword)

	if err != nil {
		return err
	}

	*o = PickUserUsernameOrPassword(varPickUserUsernameOrPassword)

	return err
}

type NullablePickUserUsernameOrPassword struct {
	value *PickUserUsernameOrPassword
	isSet bool
}

func (v NullablePickUserUsernameOrPassword) Get() *PickUserUsernameOrPassword {
	return v.value
}

func (v *NullablePickUserUsernameOrPassword) Set(val *PickUserUsernameOrPassword) {
	v.value = val
	v.isSet = true
}

func (v NullablePickUserUsernameOrPassword) IsSet() bool {
	return v.isSet
}

func (v *NullablePickUserUsernameOrPassword) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePickUserUsernameOrPassword(val *PickUserUsernameOrPassword) *NullablePickUserUsernameOrPassword {
	return &NullablePickUserUsernameOrPassword{value: val, isSet: true}
}

func (v NullablePickUserUsernameOrPassword) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePickUserUsernameOrPassword) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
