/*
api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SchoolAlreadyExistsError type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SchoolAlreadyExistsError{}

// SchoolAlreadyExistsError struct for SchoolAlreadyExistsError
type SchoolAlreadyExistsError struct {
	Message PickSchoolErrorMessageOrTypeMessage `json:"message"`
	Type SchoolErrorTypeSCHOOLALREADYEXISTS `json:"type"`
}

type _SchoolAlreadyExistsError SchoolAlreadyExistsError

// NewSchoolAlreadyExistsError instantiates a new SchoolAlreadyExistsError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSchoolAlreadyExistsError(message PickSchoolErrorMessageOrTypeMessage, type_ SchoolErrorTypeSCHOOLALREADYEXISTS) *SchoolAlreadyExistsError {
	this := SchoolAlreadyExistsError{}
	this.Message = message
	this.Type = type_
	return &this
}

// NewSchoolAlreadyExistsErrorWithDefaults instantiates a new SchoolAlreadyExistsError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSchoolAlreadyExistsErrorWithDefaults() *SchoolAlreadyExistsError {
	this := SchoolAlreadyExistsError{}
	return &this
}

// GetMessage returns the Message field value
func (o *SchoolAlreadyExistsError) GetMessage() PickSchoolErrorMessageOrTypeMessage {
	if o == nil {
		var ret PickSchoolErrorMessageOrTypeMessage
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *SchoolAlreadyExistsError) GetMessageOk() (*PickSchoolErrorMessageOrTypeMessage, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *SchoolAlreadyExistsError) SetMessage(v PickSchoolErrorMessageOrTypeMessage) {
	o.Message = v
}

// GetType returns the Type field value
func (o *SchoolAlreadyExistsError) GetType() SchoolErrorTypeSCHOOLALREADYEXISTS {
	if o == nil {
		var ret SchoolErrorTypeSCHOOLALREADYEXISTS
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *SchoolAlreadyExistsError) GetTypeOk() (*SchoolErrorTypeSCHOOLALREADYEXISTS, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *SchoolAlreadyExistsError) SetType(v SchoolErrorTypeSCHOOLALREADYEXISTS) {
	o.Type = v
}

func (o SchoolAlreadyExistsError) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SchoolAlreadyExistsError) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["message"] = o.Message
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *SchoolAlreadyExistsError) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"message",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSchoolAlreadyExistsError := _SchoolAlreadyExistsError{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSchoolAlreadyExistsError)

	if err != nil {
		return err
	}

	*o = SchoolAlreadyExistsError(varSchoolAlreadyExistsError)

	return err
}

type NullableSchoolAlreadyExistsError struct {
	value *SchoolAlreadyExistsError
	isSet bool
}

func (v NullableSchoolAlreadyExistsError) Get() *SchoolAlreadyExistsError {
	return v.value
}

func (v *NullableSchoolAlreadyExistsError) Set(val *SchoolAlreadyExistsError) {
	v.value = val
	v.isSet = true
}

func (v NullableSchoolAlreadyExistsError) IsSet() bool {
	return v.isSet
}

func (v *NullableSchoolAlreadyExistsError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSchoolAlreadyExistsError(val *SchoolAlreadyExistsError) *NullableSchoolAlreadyExistsError {
	return &NullableSchoolAlreadyExistsError{value: val, isSet: true}
}

func (v NullableSchoolAlreadyExistsError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSchoolAlreadyExistsError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


