/*
api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the DefaultSelectionPrismaCoursePayload type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DefaultSelectionPrismaCoursePayload{}

// DefaultSelectionPrismaCoursePayload struct for DefaultSelectionPrismaCoursePayload
type DefaultSelectionPrismaCoursePayload struct {
	SchoolId int32  `json:"school_id"`
	Code     string `json:"code"`
	Name     string `json:"name"`
	Id       int32  `json:"id"`
}

type _DefaultSelectionPrismaCoursePayload DefaultSelectionPrismaCoursePayload

// NewDefaultSelectionPrismaCoursePayload instantiates a new DefaultSelectionPrismaCoursePayload object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDefaultSelectionPrismaCoursePayload(schoolId int32, code string, name string, id int32) *DefaultSelectionPrismaCoursePayload {
	this := DefaultSelectionPrismaCoursePayload{}
	this.SchoolId = schoolId
	this.Code = code
	this.Name = name
	this.Id = id
	return &this
}

// NewDefaultSelectionPrismaCoursePayloadWithDefaults instantiates a new DefaultSelectionPrismaCoursePayload object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDefaultSelectionPrismaCoursePayloadWithDefaults() *DefaultSelectionPrismaCoursePayload {
	this := DefaultSelectionPrismaCoursePayload{}
	return &this
}

// GetSchoolId returns the SchoolId field value
func (o *DefaultSelectionPrismaCoursePayload) GetSchoolId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.SchoolId
}

// GetSchoolIdOk returns a tuple with the SchoolId field value
// and a boolean to check if the value has been set.
func (o *DefaultSelectionPrismaCoursePayload) GetSchoolIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SchoolId, true
}

// SetSchoolId sets field value
func (o *DefaultSelectionPrismaCoursePayload) SetSchoolId(v int32) {
	o.SchoolId = v
}

// GetCode returns the Code field value
func (o *DefaultSelectionPrismaCoursePayload) GetCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *DefaultSelectionPrismaCoursePayload) GetCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *DefaultSelectionPrismaCoursePayload) SetCode(v string) {
	o.Code = v
}

// GetName returns the Name field value
func (o *DefaultSelectionPrismaCoursePayload) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *DefaultSelectionPrismaCoursePayload) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *DefaultSelectionPrismaCoursePayload) SetName(v string) {
	o.Name = v
}

// GetId returns the Id field value
func (o *DefaultSelectionPrismaCoursePayload) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *DefaultSelectionPrismaCoursePayload) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *DefaultSelectionPrismaCoursePayload) SetId(v int32) {
	o.Id = v
}

func (o DefaultSelectionPrismaCoursePayload) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DefaultSelectionPrismaCoursePayload) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["school_id"] = o.SchoolId
	toSerialize["code"] = o.Code
	toSerialize["name"] = o.Name
	toSerialize["id"] = o.Id
	return toSerialize, nil
}

func (o *DefaultSelectionPrismaCoursePayload) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"school_id",
		"code",
		"name",
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDefaultSelectionPrismaCoursePayload := _DefaultSelectionPrismaCoursePayload{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDefaultSelectionPrismaCoursePayload)

	if err != nil {
		return err
	}

	*o = DefaultSelectionPrismaCoursePayload(varDefaultSelectionPrismaCoursePayload)

	return err
}

type NullableDefaultSelectionPrismaCoursePayload struct {
	value *DefaultSelectionPrismaCoursePayload
	isSet bool
}

func (v NullableDefaultSelectionPrismaCoursePayload) Get() *DefaultSelectionPrismaCoursePayload {
	return v.value
}

func (v *NullableDefaultSelectionPrismaCoursePayload) Set(val *DefaultSelectionPrismaCoursePayload) {
	v.value = val
	v.isSet = true
}

func (v NullableDefaultSelectionPrismaCoursePayload) IsSet() bool {
	return v.isSet
}

func (v *NullableDefaultSelectionPrismaCoursePayload) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDefaultSelectionPrismaCoursePayload(val *DefaultSelectionPrismaCoursePayload) *NullableDefaultSelectionPrismaCoursePayload {
	return &NullableDefaultSelectionPrismaCoursePayload{value: val, isSet: true}
}

func (v NullableDefaultSelectionPrismaCoursePayload) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDefaultSelectionPrismaCoursePayload) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
