/*
api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DefaultSelectionPrisma36CoursePayload type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DefaultSelectionPrisma36CoursePayload{}

// DefaultSelectionPrisma36CoursePayload struct for DefaultSelectionPrisma36CoursePayload
type DefaultSelectionPrisma36CoursePayload struct {
	SchoolId int32 `json:"school_id"`
	Code string `json:"code"`
	Name string `json:"name"`
	Id int32 `json:"id"`
}

type _DefaultSelectionPrisma36CoursePayload DefaultSelectionPrisma36CoursePayload

// NewDefaultSelectionPrisma36CoursePayload instantiates a new DefaultSelectionPrisma36CoursePayload object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDefaultSelectionPrisma36CoursePayload(schoolId int32, code string, name string, id int32) *DefaultSelectionPrisma36CoursePayload {
	this := DefaultSelectionPrisma36CoursePayload{}
	this.SchoolId = schoolId
	this.Code = code
	this.Name = name
	this.Id = id
	return &this
}

// NewDefaultSelectionPrisma36CoursePayloadWithDefaults instantiates a new DefaultSelectionPrisma36CoursePayload object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDefaultSelectionPrisma36CoursePayloadWithDefaults() *DefaultSelectionPrisma36CoursePayload {
	this := DefaultSelectionPrisma36CoursePayload{}
	return &this
}

// GetSchoolId returns the SchoolId field value
func (o *DefaultSelectionPrisma36CoursePayload) GetSchoolId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.SchoolId
}

// GetSchoolIdOk returns a tuple with the SchoolId field value
// and a boolean to check if the value has been set.
func (o *DefaultSelectionPrisma36CoursePayload) GetSchoolIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SchoolId, true
}

// SetSchoolId sets field value
func (o *DefaultSelectionPrisma36CoursePayload) SetSchoolId(v int32) {
	o.SchoolId = v
}

// GetCode returns the Code field value
func (o *DefaultSelectionPrisma36CoursePayload) GetCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *DefaultSelectionPrisma36CoursePayload) GetCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *DefaultSelectionPrisma36CoursePayload) SetCode(v string) {
	o.Code = v
}

// GetName returns the Name field value
func (o *DefaultSelectionPrisma36CoursePayload) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *DefaultSelectionPrisma36CoursePayload) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *DefaultSelectionPrisma36CoursePayload) SetName(v string) {
	o.Name = v
}

// GetId returns the Id field value
func (o *DefaultSelectionPrisma36CoursePayload) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *DefaultSelectionPrisma36CoursePayload) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *DefaultSelectionPrisma36CoursePayload) SetId(v int32) {
	o.Id = v
}

func (o DefaultSelectionPrisma36CoursePayload) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DefaultSelectionPrisma36CoursePayload) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["school_id"] = o.SchoolId
	toSerialize["code"] = o.Code
	toSerialize["name"] = o.Name
	toSerialize["id"] = o.Id
	return toSerialize, nil
}

func (o *DefaultSelectionPrisma36CoursePayload) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"school_id",
		"code",
		"name",
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDefaultSelectionPrisma36CoursePayload := _DefaultSelectionPrisma36CoursePayload{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDefaultSelectionPrisma36CoursePayload)

	if err != nil {
		return err
	}

	*o = DefaultSelectionPrisma36CoursePayload(varDefaultSelectionPrisma36CoursePayload)

	return err
}

type NullableDefaultSelectionPrisma36CoursePayload struct {
	value *DefaultSelectionPrisma36CoursePayload
	isSet bool
}

func (v NullableDefaultSelectionPrisma36CoursePayload) Get() *DefaultSelectionPrisma36CoursePayload {
	return v.value
}

func (v *NullableDefaultSelectionPrisma36CoursePayload) Set(val *DefaultSelectionPrisma36CoursePayload) {
	v.value = val
	v.isSet = true
}

func (v NullableDefaultSelectionPrisma36CoursePayload) IsSet() bool {
	return v.isSet
}

func (v *NullableDefaultSelectionPrisma36CoursePayload) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDefaultSelectionPrisma36CoursePayload(val *DefaultSelectionPrisma36CoursePayload) *NullableDefaultSelectionPrisma36CoursePayload {
	return &NullableDefaultSelectionPrisma36CoursePayload{value: val, isSet: true}
}

func (v NullableDefaultSelectionPrisma36CoursePayload) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDefaultSelectionPrisma36CoursePayload) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


