/*
api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ProfessorCourses type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProfessorCourses{}

// ProfessorCourses struct for ProfessorCourses
type ProfessorCourses struct {
	Total int32 `json:"total"`
	Courses []PickProfessorCourseExcludeKeyofProfessorCourseProfessorIdOrIdOrCourseId `json:"courses"`
}

type _ProfessorCourses ProfessorCourses

// NewProfessorCourses instantiates a new ProfessorCourses object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProfessorCourses(total int32, courses []PickProfessorCourseExcludeKeyofProfessorCourseProfessorIdOrIdOrCourseId) *ProfessorCourses {
	this := ProfessorCourses{}
	this.Total = total
	this.Courses = courses
	return &this
}

// NewProfessorCoursesWithDefaults instantiates a new ProfessorCourses object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProfessorCoursesWithDefaults() *ProfessorCourses {
	this := ProfessorCourses{}
	return &this
}

// GetTotal returns the Total field value
func (o *ProfessorCourses) GetTotal() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *ProfessorCourses) GetTotalOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *ProfessorCourses) SetTotal(v int32) {
	o.Total = v
}

// GetCourses returns the Courses field value
func (o *ProfessorCourses) GetCourses() []PickProfessorCourseExcludeKeyofProfessorCourseProfessorIdOrIdOrCourseId {
	if o == nil {
		var ret []PickProfessorCourseExcludeKeyofProfessorCourseProfessorIdOrIdOrCourseId
		return ret
	}

	return o.Courses
}

// GetCoursesOk returns a tuple with the Courses field value
// and a boolean to check if the value has been set.
func (o *ProfessorCourses) GetCoursesOk() ([]PickProfessorCourseExcludeKeyofProfessorCourseProfessorIdOrIdOrCourseId, bool) {
	if o == nil {
		return nil, false
	}
	return o.Courses, true
}

// SetCourses sets field value
func (o *ProfessorCourses) SetCourses(v []PickProfessorCourseExcludeKeyofProfessorCourseProfessorIdOrIdOrCourseId) {
	o.Courses = v
}

func (o ProfessorCourses) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProfessorCourses) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["total"] = o.Total
	toSerialize["courses"] = o.Courses
	return toSerialize, nil
}

func (o *ProfessorCourses) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"total",
		"courses",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProfessorCourses := _ProfessorCourses{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varProfessorCourses)

	if err != nil {
		return err
	}

	*o = ProfessorCourses(varProfessorCourses)

	return err
}

type NullableProfessorCourses struct {
	value *ProfessorCourses
	isSet bool
}

func (v NullableProfessorCourses) Get() *ProfessorCourses {
	return v.value
}

func (v *NullableProfessorCourses) Set(val *ProfessorCourses) {
	v.value = val
	v.isSet = true
}

func (v NullableProfessorCourses) IsSet() bool {
	return v.isSet
}

func (v *NullableProfessorCourses) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProfessorCourses(val *ProfessorCourses) *NullableProfessorCourses {
	return &NullableProfessorCourses{value: val, isSet: true}
}

func (v NullableProfessorCourses) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProfessorCourses) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


