/*
api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the DefaultSelectionPrisma36ReviewPayload type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DefaultSelectionPrisma36ReviewPayload{}

// DefaultSelectionPrisma36ReviewPayload struct for DefaultSelectionPrisma36ReviewPayload
type DefaultSelectionPrisma36ReviewPayload struct {
	ProfessorId int32                 `json:"professor_id"`
	Grade       ModelEnumsGrade       `json:"grade"`
	Tags        []ModelEnumsReviewTag `json:"tags"`
	Time        time.Time             `json:"time"`
	Difficulty  int32                 `json:"difficulty"`
	Quality     int32                 `json:"quality"`
	Id          int32                 `json:"id"`
}

type _DefaultSelectionPrisma36ReviewPayload DefaultSelectionPrisma36ReviewPayload

// NewDefaultSelectionPrisma36ReviewPayload instantiates a new DefaultSelectionPrisma36ReviewPayload object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDefaultSelectionPrisma36ReviewPayload(professorId int32, grade ModelEnumsGrade, tags []ModelEnumsReviewTag, time time.Time, difficulty int32, quality int32, id int32) *DefaultSelectionPrisma36ReviewPayload {
	this := DefaultSelectionPrisma36ReviewPayload{}
	this.ProfessorId = professorId
	this.Grade = grade
	this.Tags = tags
	this.Time = time
	this.Difficulty = difficulty
	this.Quality = quality
	this.Id = id
	return &this
}

// NewDefaultSelectionPrisma36ReviewPayloadWithDefaults instantiates a new DefaultSelectionPrisma36ReviewPayload object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDefaultSelectionPrisma36ReviewPayloadWithDefaults() *DefaultSelectionPrisma36ReviewPayload {
	this := DefaultSelectionPrisma36ReviewPayload{}
	return &this
}

// GetProfessorId returns the ProfessorId field value
func (o *DefaultSelectionPrisma36ReviewPayload) GetProfessorId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ProfessorId
}

// GetProfessorIdOk returns a tuple with the ProfessorId field value
// and a boolean to check if the value has been set.
func (o *DefaultSelectionPrisma36ReviewPayload) GetProfessorIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProfessorId, true
}

// SetProfessorId sets field value
func (o *DefaultSelectionPrisma36ReviewPayload) SetProfessorId(v int32) {
	o.ProfessorId = v
}

// GetGrade returns the Grade field value
func (o *DefaultSelectionPrisma36ReviewPayload) GetGrade() ModelEnumsGrade {
	if o == nil {
		var ret ModelEnumsGrade
		return ret
	}

	return o.Grade
}

// GetGradeOk returns a tuple with the Grade field value
// and a boolean to check if the value has been set.
func (o *DefaultSelectionPrisma36ReviewPayload) GetGradeOk() (*ModelEnumsGrade, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Grade, true
}

// SetGrade sets field value
func (o *DefaultSelectionPrisma36ReviewPayload) SetGrade(v ModelEnumsGrade) {
	o.Grade = v
}

// GetTags returns the Tags field value
func (o *DefaultSelectionPrisma36ReviewPayload) GetTags() []ModelEnumsReviewTag {
	if o == nil {
		var ret []ModelEnumsReviewTag
		return ret
	}

	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value
// and a boolean to check if the value has been set.
func (o *DefaultSelectionPrisma36ReviewPayload) GetTagsOk() ([]ModelEnumsReviewTag, bool) {
	if o == nil {
		return nil, false
	}
	return o.Tags, true
}

// SetTags sets field value
func (o *DefaultSelectionPrisma36ReviewPayload) SetTags(v []ModelEnumsReviewTag) {
	o.Tags = v
}

// GetTime returns the Time field value
func (o *DefaultSelectionPrisma36ReviewPayload) GetTime() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Time
}

// GetTimeOk returns a tuple with the Time field value
// and a boolean to check if the value has been set.
func (o *DefaultSelectionPrisma36ReviewPayload) GetTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Time, true
}

// SetTime sets field value
func (o *DefaultSelectionPrisma36ReviewPayload) SetTime(v time.Time) {
	o.Time = v
}

// GetDifficulty returns the Difficulty field value
func (o *DefaultSelectionPrisma36ReviewPayload) GetDifficulty() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Difficulty
}

// GetDifficultyOk returns a tuple with the Difficulty field value
// and a boolean to check if the value has been set.
func (o *DefaultSelectionPrisma36ReviewPayload) GetDifficultyOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Difficulty, true
}

// SetDifficulty sets field value
func (o *DefaultSelectionPrisma36ReviewPayload) SetDifficulty(v int32) {
	o.Difficulty = v
}

// GetQuality returns the Quality field value
func (o *DefaultSelectionPrisma36ReviewPayload) GetQuality() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Quality
}

// GetQualityOk returns a tuple with the Quality field value
// and a boolean to check if the value has been set.
func (o *DefaultSelectionPrisma36ReviewPayload) GetQualityOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Quality, true
}

// SetQuality sets field value
func (o *DefaultSelectionPrisma36ReviewPayload) SetQuality(v int32) {
	o.Quality = v
}

// GetId returns the Id field value
func (o *DefaultSelectionPrisma36ReviewPayload) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *DefaultSelectionPrisma36ReviewPayload) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *DefaultSelectionPrisma36ReviewPayload) SetId(v int32) {
	o.Id = v
}

func (o DefaultSelectionPrisma36ReviewPayload) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DefaultSelectionPrisma36ReviewPayload) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["professor_id"] = o.ProfessorId
	toSerialize["grade"] = o.Grade
	toSerialize["tags"] = o.Tags
	toSerialize["time"] = o.Time
	toSerialize["difficulty"] = o.Difficulty
	toSerialize["quality"] = o.Quality
	toSerialize["id"] = o.Id
	return toSerialize, nil
}

func (o *DefaultSelectionPrisma36ReviewPayload) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"professor_id",
		"grade",
		"tags",
		"time",
		"difficulty",
		"quality",
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDefaultSelectionPrisma36ReviewPayload := _DefaultSelectionPrisma36ReviewPayload{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDefaultSelectionPrisma36ReviewPayload)

	if err != nil {
		return err
	}

	*o = DefaultSelectionPrisma36ReviewPayload(varDefaultSelectionPrisma36ReviewPayload)

	return err
}

type NullableDefaultSelectionPrisma36ReviewPayload struct {
	value *DefaultSelectionPrisma36ReviewPayload
	isSet bool
}

func (v NullableDefaultSelectionPrisma36ReviewPayload) Get() *DefaultSelectionPrisma36ReviewPayload {
	return v.value
}

func (v *NullableDefaultSelectionPrisma36ReviewPayload) Set(val *DefaultSelectionPrisma36ReviewPayload) {
	v.value = val
	v.isSet = true
}

func (v NullableDefaultSelectionPrisma36ReviewPayload) IsSet() bool {
	return v.isSet
}

func (v *NullableDefaultSelectionPrisma36ReviewPayload) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDefaultSelectionPrisma36ReviewPayload(val *DefaultSelectionPrisma36ReviewPayload) *NullableDefaultSelectionPrisma36ReviewPayload {
	return &NullableDefaultSelectionPrisma36ReviewPayload{value: val, isSet: true}
}

func (v NullableDefaultSelectionPrisma36ReviewPayload) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDefaultSelectionPrisma36ReviewPayload) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
