/*
api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the NewReview type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NewReview{}

// NewReview struct for NewReview
type NewReview struct {
	Quality     float32               `json:"quality"`
	Difficulty  float32               `json:"difficulty"`
	Time        time.Time             `json:"time"`
	Tags        Model36EnumsReviewTag `json:"tags"`
	Grade       odel36EnumsGrade      `json:"grade"`
	ProfessorId int32                 `json:"professor_id"`
}

type _NewReview NewReview

// NewNewReview instantiates a new NewReview object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNewReview(quality float32, difficulty float32, time time.Time, tags []ModelEnumsReviewTag, grade ModelEnumsGrade, professorId int32) *NewReview {
	this := NewReview{}
	this.Quality = quality
	this.Difficulty = difficulty
	this.Time = time
	this.Tags = tags
	this.Grade = grade
	this.ProfessorId = professorId
	return &this
}

// NewNewReviewWithDefaults instantiates a new NewReview object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNewReviewWithDefaults() *NewReview {
	this := NewReview{}
	return &this
}

// GetQuality returns the Quality field value
func (o *NewReview) GetQuality() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Quality
}

// GetQualityOk returns a tuple with the Quality field value
// and a boolean to check if the value has been set.
func (o *NewReview) GetQualityOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Quality, true
}

// SetQuality sets field value
func (o *NewReview) SetQuality(v float32) {
	o.Quality = v
}

// GetDifficulty returns the Difficulty field value
func (o *NewReview) GetDifficulty() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Difficulty
}

// GetDifficultyOk returns a tuple with the Difficulty field value
// and a boolean to check if the value has been set.
func (o *NewReview) GetDifficultyOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Difficulty, true
}

// SetDifficulty sets field value
func (o *NewReview) SetDifficulty(v float32) {
	o.Difficulty = v
}

// GetTime returns the Time field value
func (o *NewReview) GetTime() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Time
}

// GetTimeOk returns a tuple with the Time field value
// and a boolean to check if the value has been set.
func (o *NewReview) GetTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Time, true
}

// SetTime sets field value
func (o *NewReview) SetTime(v time.Time) {
	o.Time = v
}

// GetTags returns the Tags field value
func (o *NewReview) GetTags() []ModelEnumsReviewTag {
	if o == nil {
		var ret []ModelEnumsReviewTag
		return ret
	}

	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value
// and a boolean to check if the value has been set.
func (o *NewReview) GetTagsOk() ([]ModelEnumsReviewTag, bool) {
	if o == nil {
		return nil, false
	}
	return o.Tags, true
}

// SetTags sets field value
func (o *NewReview) SetTags(v []ModelEnumsReviewTag) {
	o.Tags = v
}

// GetGrade returns the Grade field value
func (o *NewReview) GetGrade() ModelEnumsGrade {
	if o == nil {
		var ret ModelEnumsGrade
		return ret
	}

	return o.Grade
}

// GetGradeOk returns a tuple with the Grade field value
// and a boolean to check if the value has been set.
func (o *NewReview) GetGradeOk() (*ModelEnumsGrade, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Grade, true
}

// SetGrade sets field value
func (o *NewReview) SetGrade(v ModelEnumsGrade) {
	o.Grade = v
}

// GetProfessorId returns the ProfessorId field value
func (o *NewReview) GetProfessorId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ProfessorId
}

// GetProfessorIdOk returns a tuple with the ProfessorId field value
// and a boolean to check if the value has been set.
func (o *NewReview) GetProfessorIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProfessorId, true
}

// SetProfessorId sets field value
func (o *NewReview) SetProfessorId(v int32) {
	o.ProfessorId = v
}

func (o NewReview) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NewReview) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["quality"] = o.Quality
	toSerialize["difficulty"] = o.Difficulty
	toSerialize["time"] = o.Time
	toSerialize["tags"] = o.Tags
	toSerialize["grade"] = o.Grade
	toSerialize["professor_id"] = o.ProfessorId
	return toSerialize, nil
}

func (o *NewReview) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"quality",
		"difficulty",
		"time",
		"tags",
		"grade",
		"professor_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNewReview := _NewReview{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varNewReview)

	if err != nil {
		return err
	}

	*o = NewReview(varNewReview)

	return err
}

type NullableNewReview struct {
	value *NewReview
	isSet bool
}

func (v NullableNewReview) Get() *NewReview {
	return v.value
}

func (v *NullableNewReview) Set(val *NewReview) {
	v.value = val
	v.isSet = true
}

func (v NullableNewReview) IsSet() bool {
	return v.isSet
}

func (v *NullableNewReview) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNewReview(val *NewReview) *NullableNewReview {
	return &NullableNewReview{value: val, isSet: true}
}

func (v NullableNewReview) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNewReview) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
