/*
api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the DefaultSelectionPrismaReviewPayload type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DefaultSelectionPrismaReviewPayload{}

// DefaultSelectionPrismaReviewPayload struct for DefaultSelectionPrismaReviewPayload
type DefaultSelectionPrismaReviewPayload struct {
	ProfessorId int32                 `json:"professor_id"`
	Grade       ModelEnumsGrade       `json:"grade"`
	Tags        []ModelEnumsReviewTag `json:"tags"`
	Time        time.Time             `json:"time"`
	Difficulty  int32                 `json:"difficulty"`
	Quality     int32                 `json:"quality"`
	Id          int32                 `json:"id"`
}

type _DefaultSelectionPrismaReviewPayload DefaultSelectionPrismaReviewPayload

// NewDefaultSelectionPrismaReviewPayload instantiates a new DefaultSelectionPrismaReviewPayload object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDefaultSelectionPrismaReviewPayload(professorId int32, grade ModelEnumsGrade, tags []ModelEnumsReviewTag, time time.Time, difficulty int32, quality int32, id int32) *DefaultSelectionPrismaReviewPayload {
	this := DefaultSelectionPrismaReviewPayload{}
	this.ProfessorId = professorId
	this.Grade = grade
	this.Tags = tags
	this.Time = time
	this.Difficulty = difficulty
	this.Quality = quality
	this.Id = id
	return &this
}

// NewDefaultSelectionPrismaReviewPayloadWithDefaults instantiates a new DefaultSelectionPrismaReviewPayload object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDefaultSelectionPrismaReviewPayloadWithDefaults() *DefaultSelectionPrismaReviewPayload {
	this := DefaultSelectionPrismaReviewPayload{}
	return &this
}

// GetProfessorId returns the ProfessorId field value
func (o *DefaultSelectionPrismaReviewPayload) GetProfessorId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ProfessorId
}

// GetProfessorIdOk returns a tuple with the ProfessorId field value
// and a boolean to check if the value has been set.
func (o *DefaultSelectionPrismaReviewPayload) GetProfessorIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProfessorId, true
}

// SetProfessorId sets field value
func (o *DefaultSelectionPrismaReviewPayload) SetProfessorId(v int32) {
	o.ProfessorId = v
}

// GetGrade returns the Grade field value
func (o *DefaultSelectionPrismaReviewPayload) GetGrade() ModelEnumsGrade {
	if o == nil {
		var ret ModelEnumsGrade
		return ret
	}

	return o.Grade
}

// GetGradeOk returns a tuple with the Grade field value
// and a boolean to check if the value has been set.
func (o *DefaultSelectionPrismaReviewPayload) GetGradeOk() (*ModelEnumsGrade, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Grade, true
}

// SetGrade sets field value
func (o *DefaultSelectionPrismaReviewPayload) SetGrade(v ModelEnumsGrade) {
	o.Grade = v
}

// GetTags returns the Tags field value
func (o *DefaultSelectionPrismaReviewPayload) GetTags() []ModelEnumsReviewTag {
	if o == nil {
		var ret []ModelEnumsReviewTag
		return ret
	}

	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value
// and a boolean to check if the value has been set.
func (o *DefaultSelectionPrismaReviewPayload) GetTagsOk() ([]ModelEnumsReviewTag, bool) {
	if o == nil {
		return nil, false
	}
	return o.Tags, true
}

// SetTags sets field value
func (o *DefaultSelectionPrismaReviewPayload) SetTags(v []ModelEnumsReviewTag) {
	o.Tags = v
}

// GetTime returns the Time field value
func (o *DefaultSelectionPrismaReviewPayload) GetTime() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Time
}

// GetTimeOk returns a tuple with the Time field value
// and a boolean to check if the value has been set.
func (o *DefaultSelectionPrismaReviewPayload) GetTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Time, true
}

// SetTime sets field value
func (o *DefaultSelectionPrismaReviewPayload) SetTime(v time.Time) {
	o.Time = v
}

// GetDifficulty returns the Difficulty field value
func (o *DefaultSelectionPrismaReviewPayload) GetDifficulty() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Difficulty
}

// GetDifficultyOk returns a tuple with the Difficulty field value
// and a boolean to check if the value has been set.
func (o *DefaultSelectionPrismaReviewPayload) GetDifficultyOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Difficulty, true
}

// SetDifficulty sets field value
func (o *DefaultSelectionPrismaReviewPayload) SetDifficulty(v int32) {
	o.Difficulty = v
}

// GetQuality returns the Quality field value
func (o *DefaultSelectionPrismaReviewPayload) GetQuality() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Quality
}

// GetQualityOk returns a tuple with the Quality field value
// and a boolean to check if the value has been set.
func (o *DefaultSelectionPrismaReviewPayload) GetQualityOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Quality, true
}

// SetQuality sets field value
func (o *DefaultSelectionPrismaReviewPayload) SetQuality(v int32) {
	o.Quality = v
}

// GetId returns the Id field value
func (o *DefaultSelectionPrismaReviewPayload) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *DefaultSelectionPrismaReviewPayload) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *DefaultSelectionPrismaReviewPayload) SetId(v int32) {
	o.Id = v
}

func (o DefaultSelectionPrismaReviewPayload) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DefaultSelectionPrismaReviewPayload) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["professor_id"] = o.ProfessorId
	toSerialize["grade"] = o.Grade
	toSerialize["tags"] = o.Tags
	toSerialize["time"] = o.Time
	toSerialize["difficulty"] = o.Difficulty
	toSerialize["quality"] = o.Quality
	toSerialize["id"] = o.Id
	return toSerialize, nil
}

func (o *DefaultSelectionPrismaReviewPayload) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"professor_id",
		"grade",
		"tags",
		"time",
		"difficulty",
		"quality",
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDefaultSelectionPrismaReviewPayload := _DefaultSelectionPrismaReviewPayload{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDefaultSelectionPrismaReviewPayload)

	if err != nil {
		return err
	}

	*o = DefaultSelectionPrismaReviewPayload(varDefaultSelectionPrismaReviewPayload)

	return err
}

type NullableDefaultSelectionPrismaReviewPayload struct {
	value *DefaultSelectionPrismaReviewPayload
	isSet bool
}

func (v NullableDefaultSelectionPrismaReviewPayload) Get() *DefaultSelectionPrismaReviewPayload {
	return v.value
}

func (v *NullableDefaultSelectionPrismaReviewPayload) Set(val *DefaultSelectionPrismaReviewPayload) {
	v.value = val
	v.isSet = true
}

func (v NullableDefaultSelectionPrismaReviewPayload) IsSet() bool {
	return v.isSet
}

func (v *NullableDefaultSelectionPrismaReviewPayload) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDefaultSelectionPrismaReviewPayload(val *DefaultSelectionPrismaReviewPayload) *NullableDefaultSelectionPrismaReviewPayload {
	return &NullableDefaultSelectionPrismaReviewPayload{value: val, isSet: true}
}

func (v NullableDefaultSelectionPrismaReviewPayload) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDefaultSelectionPrismaReviewPayload) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
