/*
api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// EnumsSemester the model 'EnumsSemester'
type EnumsSemester string

// List of _36_Enums.Semester
const (
	SPRING EnumsSemester = "SPRING"
	SUMMER EnumsSemester = "SUMMER"
	FALL   EnumsSemester = "FALL"
)

// All allowed values of EnumsSemester enum
var AllowedEnumsSemesterEnumValues = []EnumsSemester{
	"SPRING",
	"SUMMER",
	"FALL",
}

func (v *EnumsSemester) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := EnumsSemester(value)
	for _, existing := range AllowedEnumsSemesterEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid EnumsSemester", value)
}

// NewEnumsSemesterFromValue returns a pointer to a valid EnumsSemester
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewEnumsSemesterFromValue(v string) (*EnumsSemester, error) {
	ev := EnumsSemester(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for EnumsSemester: valid values are %v", v, AllowedEnumsSemesterEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v EnumsSemester) IsValid() bool {
	for _, existing := range AllowedEnumsSemesterEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to _36_Enums.Semester value
func (v EnumsSemester) Ptr() *EnumsSemester {
	return &v
}

type NullableEnumsSemester struct {
	value *EnumsSemester
	isSet bool
}

func (v NullableEnumsSemester) Get() *EnumsSemester {
	return v.value
}

func (v *NullableEnumsSemester) Set(val *EnumsSemester) {
	v.value = val
	v.isSet = true
}

func (v NullableEnumsSemester) IsSet() bool {
	return v.isSet
}

func (v *NullableEnumsSemester) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEnumsSemester(val *EnumsSemester) *NullableEnumsSemester {
	return &NullableEnumsSemester{value: val, isSet: true}
}

func (v NullableEnumsSemester) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEnumsSemester) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
