/*
api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DefaultSelectionPrisma36SchoolPayload type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DefaultSelectionPrisma36SchoolPayload{}

// DefaultSelectionPrisma36SchoolPayload struct for DefaultSelectionPrisma36SchoolPayload
type DefaultSelectionPrisma36SchoolPayload struct {
	Name string `json:"name"`
	Id int32 `json:"id"`
}

type _DefaultSelectionPrisma36SchoolPayload DefaultSelectionPrisma36SchoolPayload

// NewDefaultSelectionPrisma36SchoolPayload instantiates a new DefaultSelectionPrisma36SchoolPayload object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDefaultSelectionPrisma36SchoolPayload(name string, id int32) *DefaultSelectionPrisma36SchoolPayload {
	this := DefaultSelectionPrisma36SchoolPayload{}
	this.Name = name
	this.Id = id
	return &this
}

// NewDefaultSelectionPrisma36SchoolPayloadWithDefaults instantiates a new DefaultSelectionPrisma36SchoolPayload object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDefaultSelectionPrisma36SchoolPayloadWithDefaults() *DefaultSelectionPrisma36SchoolPayload {
	this := DefaultSelectionPrisma36SchoolPayload{}
	return &this
}

// GetName returns the Name field value
func (o *DefaultSelectionPrisma36SchoolPayload) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *DefaultSelectionPrisma36SchoolPayload) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *DefaultSelectionPrisma36SchoolPayload) SetName(v string) {
	o.Name = v
}

// GetId returns the Id field value
func (o *DefaultSelectionPrisma36SchoolPayload) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *DefaultSelectionPrisma36SchoolPayload) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *DefaultSelectionPrisma36SchoolPayload) SetId(v int32) {
	o.Id = v
}

func (o DefaultSelectionPrisma36SchoolPayload) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DefaultSelectionPrisma36SchoolPayload) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["id"] = o.Id
	return toSerialize, nil
}

func (o *DefaultSelectionPrisma36SchoolPayload) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDefaultSelectionPrisma36SchoolPayload := _DefaultSelectionPrisma36SchoolPayload{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDefaultSelectionPrisma36SchoolPayload)

	if err != nil {
		return err
	}

	*o = DefaultSelectionPrisma36SchoolPayload(varDefaultSelectionPrisma36SchoolPayload)

	return err
}

type NullableDefaultSelectionPrisma36SchoolPayload struct {
	value *DefaultSelectionPrisma36SchoolPayload
	isSet bool
}

func (v NullableDefaultSelectionPrisma36SchoolPayload) Get() *DefaultSelectionPrisma36SchoolPayload {
	return v.value
}

func (v *NullableDefaultSelectionPrisma36SchoolPayload) Set(val *DefaultSelectionPrisma36SchoolPayload) {
	v.value = val
	v.isSet = true
}

func (v NullableDefaultSelectionPrisma36SchoolPayload) IsSet() bool {
	return v.isSet
}

func (v *NullableDefaultSelectionPrisma36SchoolPayload) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDefaultSelectionPrisma36SchoolPayload(val *DefaultSelectionPrisma36SchoolPayload) *NullableDefaultSelectionPrisma36SchoolPayload {
	return &NullableDefaultSelectionPrisma36SchoolPayload{value: val, isSet: true}
}

func (v NullableDefaultSelectionPrisma36SchoolPayload) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDefaultSelectionPrisma36SchoolPayload) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


