/*
api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the PickUserEmailOrUsernameOrPassword type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PickUserEmailOrUsernameOrPassword{}

// PickUserEmailOrUsernameOrPassword From T, pick a set of properties whose keys are in the union K
type PickUserEmailOrUsernameOrPassword struct {
	Email    string `json:"email"`
	Username string `json:"username"`
	Password string `json:"password"`
}

type _PickUserEmailOrUsernameOrPassword PickUserEmailOrUsernameOrPassword

// NewPickUserEmailOrUsernameOrPassword instantiates a new PickUserEmailOrUsernameOrPassword object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPickUserEmailOrUsernameOrPassword(email string, username string, password string) *PickUserEmailOrUsernameOrPassword {
	this := PickUserEmailOrUsernameOrPassword{}
	this.Email = email
	this.Username = username
	this.Password = password
	return &this
}

// NewPickUserEmailOrUsernameOrPasswordWithDefaults instantiates a new PickUserEmailOrUsernameOrPassword object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPickUserEmailOrUsernameOrPasswordWithDefaults() *PickUserEmailOrUsernameOrPassword {
	this := PickUserEmailOrUsernameOrPassword{}
	return &this
}

// GetEmail returns the Email field value
func (o *PickUserEmailOrUsernameOrPassword) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *PickUserEmailOrUsernameOrPassword) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *PickUserEmailOrUsernameOrPassword) SetEmail(v string) {
	o.Email = v
}

// GetUsername returns the Username field value
func (o *PickUserEmailOrUsernameOrPassword) GetUsername() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Username
}

// GetUsernameOk returns a tuple with the Username field value
// and a boolean to check if the value has been set.
func (o *PickUserEmailOrUsernameOrPassword) GetUsernameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Username, true
}

// SetUsername sets field value
func (o *PickUserEmailOrUsernameOrPassword) SetUsername(v string) {
	o.Username = v
}

// GetPassword returns the Password field value
func (o *PickUserEmailOrUsernameOrPassword) GetPassword() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Password
}

// GetPasswordOk returns a tuple with the Password field value
// and a boolean to check if the value has been set.
func (o *PickUserEmailOrUsernameOrPassword) GetPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Password, true
}

// SetPassword sets field value
func (o *PickUserEmailOrUsernameOrPassword) SetPassword(v string) {
	o.Password = v
}

func (o PickUserEmailOrUsernameOrPassword) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PickUserEmailOrUsernameOrPassword) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["email"] = o.Email
	toSerialize["username"] = o.Username
	toSerialize["password"] = o.Password
	return toSerialize, nil
}

func (o *PickUserEmailOrUsernameOrPassword) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"email",
		"username",
		"password",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPickUserEmailOrUsernameOrPassword := _PickUserEmailOrUsernameOrPassword{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPickUserEmailOrUsernameOrPassword)

	if err != nil {
		return err
	}

	*o = PickUserEmailOrUsernameOrPassword(varPickUserEmailOrUsernameOrPassword)

	return err
}

type NullablePickUserEmailOrUsernameOrPassword struct {
	value *PickUserEmailOrUsernameOrPassword
	isSet bool
}

func (v NullablePickUserEmailOrUsernameOrPassword) Get() *PickUserEmailOrUsernameOrPassword {
	return v.value
}

func (v *NullablePickUserEmailOrUsernameOrPassword) Set(val *PickUserEmailOrUsernameOrPassword) {
	v.value = val
	v.isSet = true
}

func (v NullablePickUserEmailOrUsernameOrPassword) IsSet() bool {
	return v.isSet
}

func (v *NullablePickUserEmailOrUsernameOrPassword) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePickUserEmailOrUsernameOrPassword(val *PickUserEmailOrUsernameOrPassword) *NullablePickUserEmailOrUsernameOrPassword {
	return &NullablePickUserEmailOrUsernameOrPassword{value: val, isSet: true}
}

func (v NullablePickUserEmailOrUsernameOrPassword) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePickUserEmailOrUsernameOrPassword) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
