/*
api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// CourseErrorType the model 'CourseErrorType'
type CourseErrorType string

// List of CourseErrorType
const (
	NOT_FOUND CourseErrorType = "COURSE_NOT_FOUND"
	ALREADY_EXISTS CourseErrorType = "COURSE_ALREADY_EXISTS"
)

// All allowed values of CourseErrorType enum
var AllowedCourseErrorTypeEnumValues = []CourseErrorType{
	"COURSE_NOT_FOUND",
	"COURSE_ALREADY_EXISTS",
}

func (v *CourseErrorType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := CourseErrorType(value)
	for _, existing := range AllowedCourseErrorTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid CourseErrorType", value)
}

// NewCourseErrorTypeFromValue returns a pointer to a valid CourseErrorType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewCourseErrorTypeFromValue(v string) (*CourseErrorType, error) {
	ev := CourseErrorType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for CourseErrorType: valid values are %v", v, AllowedCourseErrorTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v CourseErrorType) IsValid() bool {
	for _, existing := range AllowedCourseErrorTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to CourseErrorType value
func (v CourseErrorType) Ptr() *CourseErrorType {
	return &v
}

type NullableCourseErrorType struct {
	value *CourseErrorType
	isSet bool
}

func (v NullableCourseErrorType) Get() *CourseErrorType {
	return v.value
}

func (v *NullableCourseErrorType) Set(val *CourseErrorType) {
	v.value = val
	v.isSet = true
}

func (v NullableCourseErrorType) IsSet() bool {
	return v.isSet
}

func (v *NullableCourseErrorType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCourseErrorType(val *CourseErrorType) *NullableCourseErrorType {
	return &NullableCourseErrorType{value: val, isSet: true}
}

func (v NullableCourseErrorType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCourseErrorType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

