/*
api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PickSchoolErrorMessageOrType type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PickSchoolErrorMessageOrType{}

// PickSchoolErrorMessageOrType From T, pick a set of properties whose keys are in the union K
type PickSchoolErrorMessageOrType struct {
	Message PickSchoolErrorMessageOrTypeMessage `json:"message"`
	Type SchoolErrorType `json:"type"`
}

type _PickSchoolErrorMessageOrType PickSchoolErrorMessageOrType

// NewPickSchoolErrorMessageOrType instantiates a new PickSchoolErrorMessageOrType object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPickSchoolErrorMessageOrType(message PickSchoolErrorMessageOrTypeMessage, type_ SchoolErrorType) *PickSchoolErrorMessageOrType {
	this := PickSchoolErrorMessageOrType{}
	this.Message = message
	this.Type = type_
	return &this
}

// NewPickSchoolErrorMessageOrTypeWithDefaults instantiates a new PickSchoolErrorMessageOrType object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPickSchoolErrorMessageOrTypeWithDefaults() *PickSchoolErrorMessageOrType {
	this := PickSchoolErrorMessageOrType{}
	return &this
}

// GetMessage returns the Message field value
func (o *PickSchoolErrorMessageOrType) GetMessage() PickSchoolErrorMessageOrTypeMessage {
	if o == nil {
		var ret PickSchoolErrorMessageOrTypeMessage
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *PickSchoolErrorMessageOrType) GetMessageOk() (*PickSchoolErrorMessageOrTypeMessage, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *PickSchoolErrorMessageOrType) SetMessage(v PickSchoolErrorMessageOrTypeMessage) {
	o.Message = v
}

// GetType returns the Type field value
func (o *PickSchoolErrorMessageOrType) GetType() SchoolErrorType {
	if o == nil {
		var ret SchoolErrorType
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *PickSchoolErrorMessageOrType) GetTypeOk() (*SchoolErrorType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *PickSchoolErrorMessageOrType) SetType(v SchoolErrorType) {
	o.Type = v
}

func (o PickSchoolErrorMessageOrType) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PickSchoolErrorMessageOrType) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["message"] = o.Message
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *PickSchoolErrorMessageOrType) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"message",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPickSchoolErrorMessageOrType := _PickSchoolErrorMessageOrType{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPickSchoolErrorMessageOrType)

	if err != nil {
		return err
	}

	*o = PickSchoolErrorMessageOrType(varPickSchoolErrorMessageOrType)

	return err
}

type NullablePickSchoolErrorMessageOrType struct {
	value *PickSchoolErrorMessageOrType
	isSet bool
}

func (v NullablePickSchoolErrorMessageOrType) Get() *PickSchoolErrorMessageOrType {
	return v.value
}

func (v *NullablePickSchoolErrorMessageOrType) Set(val *PickSchoolErrorMessageOrType) {
	v.value = val
	v.isSet = true
}

func (v NullablePickSchoolErrorMessageOrType) IsSet() bool {
	return v.isSet
}

func (v *NullablePickSchoolErrorMessageOrType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePickSchoolErrorMessageOrType(val *PickSchoolErrorMessageOrType) *NullablePickSchoolErrorMessageOrType {
	return &NullablePickSchoolErrorMessageOrType{value: val, isSet: true}
}

func (v NullablePickSchoolErrorMessageOrType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePickSchoolErrorMessageOrType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


