/*
api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// 36EnumsGrade the model '36EnumsGrade'
type 36EnumsGrade string

// List of _36_Enums.Grade
const (
	A_PLUS 36EnumsGrade = "A_PLUS"
	A 36EnumsGrade = "A"
	A_MINUS 36EnumsGrade = "A_MINUS"
	B_PLUS 36EnumsGrade = "B_PLUS"
	B 36EnumsGrade = "B"
	B_MINUS 36EnumsGrade = "B_MINUS"
	C_PLUS 36EnumsGrade = "C_PLUS"
	C 36EnumsGrade = "C"
	C_MINUS 36EnumsGrade = "C_MINUS"
	D_PLUS 36EnumsGrade = "D_PLUS"
	D 36EnumsGrade = "D"
	D_MINUS 36EnumsGrade = "D_MINUS"
	F_PLUS 36EnumsGrade = "F_PLUS"
	F 36EnumsGrade = "F"
	F_MINUS 36EnumsGrade = "F_MINUS"
	INCOMPLETE 36EnumsGrade = "INCOMPLETE"
	WITHDRAWN 36EnumsGrade = "WITHDRAWN"
	NOT_SURE 36EnumsGrade = "NOT_SURE"
	OTHER 36EnumsGrade = "OTHER"
)

// All allowed values of 36EnumsGrade enum
var Allowed36EnumsGradeEnumValues = []36EnumsGrade{
	"A_PLUS",
	"A",
	"A_MINUS",
	"B_PLUS",
	"B",
	"B_MINUS",
	"C_PLUS",
	"C",
	"C_MINUS",
	"D_PLUS",
	"D",
	"D_MINUS",
	"F_PLUS",
	"F",
	"F_MINUS",
	"INCOMPLETE",
	"WITHDRAWN",
	"NOT_SURE",
	"OTHER",
}

func (v *36EnumsGrade) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := 36EnumsGrade(value)
	for _, existing := range Allowed36EnumsGradeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid 36EnumsGrade", value)
}

// New36EnumsGradeFromValue returns a pointer to a valid 36EnumsGrade
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func New36EnumsGradeFromValue(v string) (*36EnumsGrade, error) {
	ev := 36EnumsGrade(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for 36EnumsGrade: valid values are %v", v, Allowed36EnumsGradeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v 36EnumsGrade) IsValid() bool {
	for _, existing := range Allowed36EnumsGradeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to _36_Enums.Grade value
func (v 36EnumsGrade) Ptr() *36EnumsGrade {
	return &v
}

type Nullable36EnumsGrade struct {
	value *36EnumsGrade
	isSet bool
}

func (v Nullable36EnumsGrade) Get() *36EnumsGrade {
	return v.value
}

func (v *Nullable36EnumsGrade) Set(val *36EnumsGrade) {
	v.value = val
	v.isSet = true
}

func (v Nullable36EnumsGrade) IsSet() bool {
	return v.isSet
}

func (v *Nullable36EnumsGrade) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullable36EnumsGrade(val *36EnumsGrade) *Nullable36EnumsGrade {
	return &Nullable36EnumsGrade{value: val, isSet: true}
}

func (v Nullable36EnumsGrade) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *Nullable36EnumsGrade) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

