/*
api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PickAuthErrorMessageOrType type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PickAuthErrorMessageOrType{}

// PickAuthErrorMessageOrType From T, pick a set of properties whose keys are in the union K
type PickAuthErrorMessageOrType struct {
	Message PickSchoolErrorMessageOrTypeMessage `json:"message"`
	Type AuthErrorType `json:"type"`
}

type _PickAuthErrorMessageOrType PickAuthErrorMessageOrType

// NewPickAuthErrorMessageOrType instantiates a new PickAuthErrorMessageOrType object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPickAuthErrorMessageOrType(message PickSchoolErrorMessageOrTypeMessage, type_ AuthErrorType) *PickAuthErrorMessageOrType {
	this := PickAuthErrorMessageOrType{}
	this.Message = message
	this.Type = type_
	return &this
}

// NewPickAuthErrorMessageOrTypeWithDefaults instantiates a new PickAuthErrorMessageOrType object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPickAuthErrorMessageOrTypeWithDefaults() *PickAuthErrorMessageOrType {
	this := PickAuthErrorMessageOrType{}
	return &this
}

// GetMessage returns the Message field value
func (o *PickAuthErrorMessageOrType) GetMessage() PickSchoolErrorMessageOrTypeMessage {
	if o == nil {
		var ret PickSchoolErrorMessageOrTypeMessage
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *PickAuthErrorMessageOrType) GetMessageOk() (*PickSchoolErrorMessageOrTypeMessage, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *PickAuthErrorMessageOrType) SetMessage(v PickSchoolErrorMessageOrTypeMessage) {
	o.Message = v
}

// GetType returns the Type field value
func (o *PickAuthErrorMessageOrType) GetType() AuthErrorType {
	if o == nil {
		var ret AuthErrorType
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *PickAuthErrorMessageOrType) GetTypeOk() (*AuthErrorType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *PickAuthErrorMessageOrType) SetType(v AuthErrorType) {
	o.Type = v
}

func (o PickAuthErrorMessageOrType) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PickAuthErrorMessageOrType) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["message"] = o.Message
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *PickAuthErrorMessageOrType) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"message",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPickAuthErrorMessageOrType := _PickAuthErrorMessageOrType{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPickAuthErrorMessageOrType)

	if err != nil {
		return err
	}

	*o = PickAuthErrorMessageOrType(varPickAuthErrorMessageOrType)

	return err
}

type NullablePickAuthErrorMessageOrType struct {
	value *PickAuthErrorMessageOrType
	isSet bool
}

func (v NullablePickAuthErrorMessageOrType) Get() *PickAuthErrorMessageOrType {
	return v.value
}

func (v *NullablePickAuthErrorMessageOrType) Set(val *PickAuthErrorMessageOrType) {
	v.value = val
	v.isSet = true
}

func (v NullablePickAuthErrorMessageOrType) IsSet() bool {
	return v.isSet
}

func (v *NullablePickAuthErrorMessageOrType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePickAuthErrorMessageOrType(val *PickAuthErrorMessageOrType) *NullablePickAuthErrorMessageOrType {
	return &NullablePickAuthErrorMessageOrType{value: val, isSet: true}
}

func (v NullablePickAuthErrorMessageOrType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePickAuthErrorMessageOrType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


