/*
api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the DefaultSelectionPrismaProfessorPayload type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DefaultSelectionPrismaProfessorPayload{}

// DefaultSelectionPrismaProfessorPayload struct for DefaultSelectionPrismaProfessorPayload
type DefaultSelectionPrismaProfessorPayload struct {
	SchoolId  int32  `json:"school_id"`
	RmpId     string `json:"rmp_id"`
	LastName  string `json:"last_name"`
	FirstName string `json:"first_name"`
	Id        int32  `json:"id"`
}

type _DefaultSelectionPrismaProfessorPayload DefaultSelectionPrismaProfessorPayload

// NewDefaultSelectionPrismaProfessorPayload instantiates a new DefaultSelectionPrismaProfessorPayload object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDefaultSelectionPrismaProfessorPayload(schoolId int32, rmpId string, lastName string, firstName string, id int32) *DefaultSelectionPrismaProfessorPayload {
	this := DefaultSelectionPrismaProfessorPayload{}
	this.SchoolId = schoolId
	this.RmpId = rmpId
	this.LastName = lastName
	this.FirstName = firstName
	this.Id = id
	return &this
}

// NewDefaultSelectionPrismaProfessorPayloadWithDefaults instantiates a new DefaultSelectionPrismaProfessorPayload object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDefaultSelectionPrismaProfessorPayloadWithDefaults() *DefaultSelectionPrismaProfessorPayload {
	this := DefaultSelectionPrismaProfessorPayload{}
	return &this
}

// GetSchoolId returns the SchoolId field value
func (o *DefaultSelectionPrismaProfessorPayload) GetSchoolId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.SchoolId
}

// GetSchoolIdOk returns a tuple with the SchoolId field value
// and a boolean to check if the value has been set.
func (o *DefaultSelectionPrismaProfessorPayload) GetSchoolIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SchoolId, true
}

// SetSchoolId sets field value
func (o *DefaultSelectionPrismaProfessorPayload) SetSchoolId(v int32) {
	o.SchoolId = v
}

// GetRmpId returns the RmpId field value
func (o *DefaultSelectionPrismaProfessorPayload) GetRmpId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RmpId
}

// GetRmpIdOk returns a tuple with the RmpId field value
// and a boolean to check if the value has been set.
func (o *DefaultSelectionPrismaProfessorPayload) GetRmpIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RmpId, true
}

// SetRmpId sets field value
func (o *DefaultSelectionPrismaProfessorPayload) SetRmpId(v string) {
	o.RmpId = v
}

// GetLastName returns the LastName field value
func (o *DefaultSelectionPrismaProfessorPayload) GetLastName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LastName
}

// GetLastNameOk returns a tuple with the LastName field value
// and a boolean to check if the value has been set.
func (o *DefaultSelectionPrismaProfessorPayload) GetLastNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LastName, true
}

// SetLastName sets field value
func (o *DefaultSelectionPrismaProfessorPayload) SetLastName(v string) {
	o.LastName = v
}

// GetFirstName returns the FirstName field value
func (o *DefaultSelectionPrismaProfessorPayload) GetFirstName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FirstName
}

// GetFirstNameOk returns a tuple with the FirstName field value
// and a boolean to check if the value has been set.
func (o *DefaultSelectionPrismaProfessorPayload) GetFirstNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FirstName, true
}

// SetFirstName sets field value
func (o *DefaultSelectionPrismaProfessorPayload) SetFirstName(v string) {
	o.FirstName = v
}

// GetId returns the Id field value
func (o *DefaultSelectionPrismaProfessorPayload) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *DefaultSelectionPrismaProfessorPayload) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *DefaultSelectionPrismaProfessorPayload) SetId(v int32) {
	o.Id = v
}

func (o DefaultSelectionPrismaProfessorPayload) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DefaultSelectionPrismaProfessorPayload) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["school_id"] = o.SchoolId
	toSerialize["rmp_id"] = o.RmpId
	toSerialize["last_name"] = o.LastName
	toSerialize["first_name"] = o.FirstName
	toSerialize["id"] = o.Id
	return toSerialize, nil
}

func (o *DefaultSelectionPrismaProfessorPayload) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"school_id",
		"rmp_id",
		"last_name",
		"first_name",
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDefaultSelectionPrismaProfessorPayload := _DefaultSelectionPrismaProfessorPayload{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDefaultSelectionPrismaProfessorPayload)

	if err != nil {
		return err
	}

	*o = DefaultSelectionPrismaProfessorPayload(varDefaultSelectionPrismaProfessorPayload)

	return err
}

type NullableDefaultSelectionPrismaProfessorPayload struct {
	value *DefaultSelectionPrismaProfessorPayload
	isSet bool
}

func (v NullableDefaultSelectionPrismaProfessorPayload) Get() *DefaultSelectionPrismaProfessorPayload {
	return v.value
}

func (v *NullableDefaultSelectionPrismaProfessorPayload) Set(val *DefaultSelectionPrismaProfessorPayload) {
	v.value = val
	v.isSet = true
}

func (v NullableDefaultSelectionPrismaProfessorPayload) IsSet() bool {
	return v.isSet
}

func (v *NullableDefaultSelectionPrismaProfessorPayload) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDefaultSelectionPrismaProfessorPayload(val *DefaultSelectionPrismaProfessorPayload) *NullableDefaultSelectionPrismaProfessorPayload {
	return &NullableDefaultSelectionPrismaProfessorPayload{value: val, isSet: true}
}

func (v NullableDefaultSelectionPrismaProfessorPayload) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDefaultSelectionPrismaProfessorPayload) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
