/*
api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the UserNotFoundError type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserNotFoundError{}

// UserNotFoundError struct for UserNotFoundError
type UserNotFoundError struct {
	Message PickSchoolErrorMessageOrTypeMessage `json:"message"`
	Type    AuthErrorTypeUSERNOTFOUND           `json:"type"`
}

type _UserNotFoundError UserNotFoundError

// NewUserNotFoundError instantiates a new UserNotFoundError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserNotFoundError(message PickSchoolErrorMessageOrTypeMessage, type_ AuthErrorTypeUSERNOTFOUND) *UserNotFoundError {
	this := UserNotFoundError{}
	this.Message = message
	this.Type = type_
	return &this
}

// NewUserNotFoundErrorWithDefaults instantiates a new UserNotFoundError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserNotFoundErrorWithDefaults() *UserNotFoundError {
	this := UserNotFoundError{}
	return &this
}

// GetMessage returns the Message field value
func (o *UserNotFoundError) GetMessage() PickSchoolErrorMessageOrTypeMessage {
	if o == nil {
		var ret PickSchoolErrorMessageOrTypeMessage
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *UserNotFoundError) GetMessageOk() (*PickSchoolErrorMessageOrTypeMessage, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *UserNotFoundError) SetMessage(v PickSchoolErrorMessageOrTypeMessage) {
	o.Message = v
}

// GetType returns the Type field value
func (o *UserNotFoundError) GetType() AuthErrorTypeUSERNOTFOUND {
	if o == nil {
		var ret AuthErrorTypeUSERNOTFOUND
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *UserNotFoundError) GetTypeOk() (*AuthErrorTypeUSERNOTFOUND, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *UserNotFoundError) SetType(v AuthErrorTypeUSERNOTFOUND) {
	o.Type = v
}

func (o UserNotFoundError) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserNotFoundError) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["message"] = o.Message
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *UserNotFoundError) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"message",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUserNotFoundError := _UserNotFoundError{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUserNotFoundError)

	if err != nil {
		return err
	}

	*o = UserNotFoundError(varUserNotFoundError)

	return err
}

type NullableUserNotFoundError struct {
	value *UserNotFoundError
	isSet bool
}

func (v NullableUserNotFoundError) Get() *UserNotFoundError {
	return v.value
}

func (v *NullableUserNotFoundError) Set(val *UserNotFoundError) {
	v.value = val
	v.isSet = true
}

func (v NullableUserNotFoundError) IsSet() bool {
	return v.isSet
}

func (v *NullableUserNotFoundError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserNotFoundError(val *UserNotFoundError) *NullableUserNotFoundError {
	return &NullableUserNotFoundError{value: val, isSet: true}
}

func (v NullableUserNotFoundError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserNotFoundError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
