/*
api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ChartValue type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ChartValue{}

// ChartValue struct for ChartValue
type ChartValue struct {
	Year float64 `json:"year"`
	Month string `json:"month"`
	Value float64 `json:"value"`
}

type _ChartValue ChartValue

// NewChartValue instantiates a new ChartValue object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChartValue(year float64, month string, value float64) *ChartValue {
	this := ChartValue{}
	this.Year = year
	this.Month = month
	this.Value = value
	return &this
}

// NewChartValueWithDefaults instantiates a new ChartValue object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChartValueWithDefaults() *ChartValue {
	this := ChartValue{}
	return &this
}

// GetYear returns the Year field value
func (o *ChartValue) GetYear() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.Year
}

// GetYearOk returns a tuple with the Year field value
// and a boolean to check if the value has been set.
func (o *ChartValue) GetYearOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Year, true
}

// SetYear sets field value
func (o *ChartValue) SetYear(v float64) {
	o.Year = v
}

// GetMonth returns the Month field value
func (o *ChartValue) GetMonth() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Month
}

// GetMonthOk returns a tuple with the Month field value
// and a boolean to check if the value has been set.
func (o *ChartValue) GetMonthOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Month, true
}

// SetMonth sets field value
func (o *ChartValue) SetMonth(v string) {
	o.Month = v
}

// GetValue returns the Value field value
func (o *ChartValue) GetValue() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *ChartValue) GetValueOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *ChartValue) SetValue(v float64) {
	o.Value = v
}

func (o ChartValue) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ChartValue) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["year"] = o.Year
	toSerialize["month"] = o.Month
	toSerialize["value"] = o.Value
	return toSerialize, nil
}

func (o *ChartValue) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"year",
		"month",
		"value",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varChartValue := _ChartValue{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varChartValue)

	if err != nil {
		return err
	}

	*o = ChartValue(varChartValue)

	return err
}

type NullableChartValue struct {
	value *ChartValue
	isSet bool
}

func (v NullableChartValue) Get() *ChartValue {
	return v.value
}

func (v *NullableChartValue) Set(val *ChartValue) {
	v.value = val
	v.isSet = true
}

func (v NullableChartValue) IsSet() bool {
	return v.isSet
}

func (v *NullableChartValue) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChartValue(val *ChartValue) *NullableChartValue {
	return &NullableChartValue{value: val, isSet: true}
}

func (v NullableChartValue) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChartValue) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


