/*
api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the PickCourseNameOrCode type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PickCourseNameOrCode{}

// PickCourseNameOrCode From T, pick a set of properties whose keys are in the union K
type PickCourseNameOrCode struct {
	Name string `json:"name"`
	Code string `json:"code"`
}

type _PickCourseNameOrCode PickCourseNameOrCode

// NewPickCourseNameOrCode instantiates a new PickCourseNameOrCode object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPickCourseNameOrCode(name string, code string) *PickCourseNameOrCode {
	this := PickCourseNameOrCode{}
	this.Name = name
	this.Code = code
	return &this
}

// NewPickCourseNameOrCodeWithDefaults instantiates a new PickCourseNameOrCode object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPickCourseNameOrCodeWithDefaults() *PickCourseNameOrCode {
	this := PickCourseNameOrCode{}
	return &this
}

// GetName returns the Name field value
func (o *PickCourseNameOrCode) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *PickCourseNameOrCode) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *PickCourseNameOrCode) SetName(v string) {
	o.Name = v
}

// GetCode returns the Code field value
func (o *PickCourseNameOrCode) GetCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *PickCourseNameOrCode) GetCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *PickCourseNameOrCode) SetCode(v string) {
	o.Code = v
}

func (o PickCourseNameOrCode) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PickCourseNameOrCode) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["code"] = o.Code
	return toSerialize, nil
}

func (o *PickCourseNameOrCode) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"code",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPickCourseNameOrCode := _PickCourseNameOrCode{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPickCourseNameOrCode)

	if err != nil {
		return err
	}

	*o = PickCourseNameOrCode(varPickCourseNameOrCode)

	return err
}

type NullablePickCourseNameOrCode struct {
	value *PickCourseNameOrCode
	isSet bool
}

func (v NullablePickCourseNameOrCode) Get() *PickCourseNameOrCode {
	return v.value
}

func (v *NullablePickCourseNameOrCode) Set(val *PickCourseNameOrCode) {
	v.value = val
	v.isSet = true
}

func (v NullablePickCourseNameOrCode) IsSet() bool {
	return v.isSet
}

func (v *NullablePickCourseNameOrCode) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePickCourseNameOrCode(val *PickCourseNameOrCode) *NullablePickCourseNameOrCode {
	return &NullablePickCourseNameOrCode{value: val, isSet: true}
}

func (v NullablePickCourseNameOrCode) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePickCourseNameOrCode) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
