/*
api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the SchoolNotFoundError type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SchoolNotFoundError{}

// SchoolNotFoundError struct for SchoolNotFoundError
type SchoolNotFoundError struct {
	Message PickSchoolErrorMessageOrTypeMessage `json:"message"`
	Type    SchoolErrorTypeSCHOOLNOTFOUND       `json:"type"`
}

type _SchoolNotFoundError SchoolNotFoundError

// NewSchoolNotFoundError instantiates a new SchoolNotFoundError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSchoolNotFoundError(message PickSchoolErrorMessageOrTypeMessage, type_ SchoolErrorTypeSCHOOLNOTFOUND) *SchoolNotFoundError {
	this := SchoolNotFoundError{}
	this.Message = message
	this.Type = type_
	return &this
}

// NewSchoolNotFoundErrorWithDefaults instantiates a new SchoolNotFoundError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSchoolNotFoundErrorWithDefaults() *SchoolNotFoundError {
	this := SchoolNotFoundError{}
	return &this
}

// GetMessage returns the Message field value
func (o *SchoolNotFoundError) GetMessage() PickSchoolErrorMessageOrTypeMessage {
	if o == nil {
		var ret PickSchoolErrorMessageOrTypeMessage
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *SchoolNotFoundError) GetMessageOk() (*PickSchoolErrorMessageOrTypeMessage, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *SchoolNotFoundError) SetMessage(v PickSchoolErrorMessageOrTypeMessage) {
	o.Message = v
}

// GetType returns the Type field value
func (o *SchoolNotFoundError) GetType() SchoolErrorTypeSCHOOLNOTFOUND {
	if o == nil {
		var ret SchoolErrorTypeSCHOOLNOTFOUND
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *SchoolNotFoundError) GetTypeOk() (*SchoolErrorTypeSCHOOLNOTFOUND, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *SchoolNotFoundError) SetType(v SchoolErrorTypeSCHOOLNOTFOUND) {
	o.Type = v
}

func (o SchoolNotFoundError) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SchoolNotFoundError) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["message"] = o.Message
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *SchoolNotFoundError) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"message",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSchoolNotFoundError := _SchoolNotFoundError{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSchoolNotFoundError)

	if err != nil {
		return err
	}

	*o = SchoolNotFoundError(varSchoolNotFoundError)

	return err
}

type NullableSchoolNotFoundError struct {
	value *SchoolNotFoundError
	isSet bool
}

func (v NullableSchoolNotFoundError) Get() *SchoolNotFoundError {
	return v.value
}

func (v *NullableSchoolNotFoundError) Set(val *SchoolNotFoundError) {
	v.value = val
	v.isSet = true
}

func (v NullableSchoolNotFoundError) IsSet() bool {
	return v.isSet
}

func (v *NullableSchoolNotFoundError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSchoolNotFoundError(val *SchoolNotFoundError) *NullableSchoolNotFoundError {
	return &NullableSchoolNotFoundError{value: val, isSet: true}
}

func (v NullableSchoolNotFoundError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSchoolNotFoundError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
